# Generated by Django 2.2.3 on 2019-07-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190731_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_num',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='max_toppings',
            field=models.SmallIntegerField(default=None),
        ),
    ]
