# Generated by Django 2.2.3 on 2019-07-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190731_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='max_toppings',
            field=models.SmallIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price_lg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price_sm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
