# Generated by Django 2.2.3 on 2019-07-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190731_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='order_num',
            field=models.SmallIntegerField(default=0),
        ),
    ]
