# Generated by Django 2.2.3 on 2019-07-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_topping_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='has_extras',
            field=models.BooleanField(default=False),
        ),
    ]
