# Generated by Django 2.2.3 on 2019-07-31 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
    ]
